skypeweb/Makefile, skypeweb/purple-skypeweb.spec
Added -install section in default makefile (needed by RPM-build).
Added SPEC for rpmbuild. RPM packages for Fedora 20+, CentOS, RHEL and openSUSE can be built by `rpmbuild -ba purple-skypeweb.spec`.
=> Added SPEC for rpmbuild

libskype.c
I have found it slightly annoying when pidgin updates skype status every time I go away. It spams my windows/OS X friends with a lot of messages in a skype timeline.
=> Added options to disable displaying of video capability status and updating of skype status message

skypeweb/README.md, skypeweb/purple-skypeweb.spec
Separated packages. Now can be used with other libpurple-based clients without Pidgin being installed.
Rpmbuild will now build two packages: purple-skypeweb and pidgin-skypeweb. First contains only plugin. Graphics and smiley themes can be found in second.
=> RPM spec file updates

skypeweb/skypeweb_contacts.c
Rename the labels to fit with libtransport and be compatible with Spectrum.
See https://github.com/hanzz/libtransport/blob/master/backends/libpurple/main.cpp#L1204
=> Rename some labels

skypeweb/.gitignore, skypeweb/libskypeweb.c, skypeweb/skypeweb_login.c
Don't become connected without valid registration token
The signed-on event fired before we connected to Skype in cases where the registration token wasn't valid. This led to clients thinking they could operated as if the user was logged in (send messages etc.) when they could not. The status change now lives in do_all_the_things(), where it only takes place if there is a valid registration.
=> Connection status fix

skypeweb/skypeweb_messages.c
The message sending code expected a "chatname" attribute to be set on chats to which message were sent. When the chat-joined event fired, this attribute was not set. This caused sending messages from a chat-joined callback to fail.
This commit fixes this issue by attempting to fall back to the name field on the conversation if the "chatname" attribute is not set.
=> Fix an issue where a chat was joined but messages couldn't be sent

skypeweb/README.md, skypeweb/purple-skypeweb.spec
fixes spec for [work with OBS] (https://build.opensuse.org/package/show/home:BOPOHA/purple-skypeweb) + creating RPMs from main tarball master.tar.gz .
It's needed for creating [ready to use] (https://software.opensuse.org/download.html?project=home%3ABOPOHA&package=purple-skypeweb) package repositories.
=> fix for auto-build packages

skypeweb/Makefile
This commit changes the Makefile to use a more standard set of variables, and more standard Makefile logic than how it was before. This makes it easier for source-based Linux distributions to package, and puts it more in line with standards set by autoconf and friends.
- COMPILER -> CC
- pkg-config -> PKG_CONFIG
- default CFLAGS -> CFLAGS, overwritten if set
=> skypeweb/Makefile: standardize

skypeweb/purple-skypeweb.spec
Fixed meta package build after applying OBS patches into spec file. Added ability to install separate packages without meta package skype4pidgin.
=> Fixed meta package build after OBS applying patches into spec file.

skypeweb/libskypeweb.c, skypeweb/libskypeweb.h, skypeweb/skypeweb_messages.c
Here is some changes to resolve issue https://github.com/EionRobb/skype4pidgin/issues/328
Some notes:
* two new options added to account settings, first enables "buddy typing ..." message when someone typing, second - will change buddy status icon to 'Voice' when he typing
* not sure is empty option needed
* only two roles allowed in new unmoderated chats: *admin* and *user*,  so I changed their default flags to OP and HALFOP and played a bit with other flags to return their original status flags when message finally typed and sent
=> Some notification settings to handle "Control/Typing" events

skypeweb/purple-skypeweb.spec
When packaging for OpenSUSE, it is required that all folders which are not part of the general filesystem to be owned by the package too. If the folders are missing, the package building fails on openSUSE's Open Build System.
This adds the missing folders to the list in the spec file so it can be used in obs without any changes for both Fedora and OpenSUSE.
=> [SkypeWeb] Add missing files to spec file list

skypeweb/libskypeweb.c, skypeweb/libskypeweb.h, skypeweb/skypeweb_contacts.c, skypeweb/skypeweb_login.c, skypeweb/skypeweb_messages.c, skypeweb/skypeweb_util.c, skypeweb/skypeweb_util.h
Fixes use-after-free bugs when the callback is called after the account is turned off.
This creates a wrapper function `skypeweb_fetch_url_request()` which takes a `SkypeWebAccount` instead of a `PurpleAccount`, and stores each return value in a linked list, `sa->url_datas`. The callbacks must take care of removing this entry.
The linked list idea is pretty much copy-pasted from built-in prpls, main difference is that others don't have a wrapper function.
This diff is rather repetitive, but it's as good as it gets.
=> Keep track of PurpleUtilFetchUrlData and cancel them on logout

skypeweb/libskypeweb.c, skypeweb/libskypeweb.h, skypeweb/skypeweb_contacts.c, skypeweb/skypeweb_messages.c
Looks valgrind clean to me now (after adding all the libpurple/gtk/cairo/rsvg/pixmap crap to suppressions...)
The `purple_find_buddies()` thing is almost-copied from a loop in `_purple_connection_destroy()` that is nulling the buddy protocol data before `prpl_info->buddy_free` is called. It sucks but it's also what it seems to expect the close prpl to do.
Quoting myself thinking aloud in the devel channel before reaching that conclusion:
>08:57 < dx> not sure what to do about this leak. account_disconnect happens before blist_uninit. the former sets buddy->proto_data to null, the latter calls prpl_info->buddy_free and finds a null, so it doesn't do anything. http://dump.dequis.org/MHbo1.txt
>09:01 < dx> hmmm http://dump.dequis.org/JDM8d.txt "that was freed in the prpl close method"
It …
=> Some small leak fixes

skypeweb/Makefile.eion, skypeweb/Makefile.msys2, skypeweb/pidgin-skypeweb.nsi
The installer is now customizable as to which Pidgin variant it will be targeted against. SkypeWeb now builds under MSYS2 too. The `Makefile.eion` should continue working the same way. Example for producing installers for both Pidgin and Pidgin++:
```
$ make -f Makefile.msys2 PIDGIN_BUILD_DIR="/somewhere"
$ make -f Makefile.msys2 PIDGIN_BUILD_DIR="/somewhere" PIDGIN_VARIANT="Pidgin++"
```
=> MSYS2 build and Pidgin variant support for SkypeWeb

skypeweb/README.md, skypeweb/purple-skypeweb.spec
* Synced SPEC with upstream.
* Now using Fedora guidelines.
* Can be built with Fedora COPR and Koji: https://copr.fedoraproject.org/coprs/xvitaly/purple-skypeweb/build/143244/
* Debug info will be stripped by RPMBuild automatically.
* Added license and readme (required by Fedora upstream).
=> Synced SPEC with upstream

skypeweb/skypeweb_contacts.c
`purple_imgstore_add_with_id()` borrows the reference to the image data, so passing a copy is needed to avoid double-free when the http request is cancelled and when the last reference to the imgstore entry is removed.
In the case of clients like bitlbee which don't keep a reference to the imgstore entry, this can mean an instant crash.
Fixes #374
=> skypeweb_got_imagemessage: Pass a copy of the data to the imgstore

po/ru.po
There is no word "свежия" in Russian :)
=> Fixed typo in russian translation

skypeweb/README.md
* Purple-skypeweb package is now available in main Fedora's repository (and EPEL7).
* Updated install HOWTO.
=> Updated README for Fedora

skypeweb/README.md
https://software.opensuse.org/package/skype4pidgin has been available since the early versions.
=> Added the openSUSE package

skypeweb/skypeweb_contacts.c
Fix this bug 
"(Pidgin:19936): Json-CRITICAL **: json_object_has_member: assertion `object != NULL' failed"
This happen when contacts are loaded and appear on advanced debug.
=> Update skypeweb_contacts.c json_object_has_member bug fix

skypeweb/skypeweb_messages.c
fix Event\Call handler, and add Signal/Flamingo (Web API) call handler
=> show system message when call received 

skypeweb/libskypeweb.c, skypeweb/skypeweb_login.c, skypeweb/skypeweb_login.h
These methods return better error messages, should be better at handling
reconnections (because only obvious auth errors are marked as such), and
will probably work with 2FA when combined with app passwords.
This adds two closely related methods that return skypetokens in a
fairly straightforward way.
- For skype usernames: api.skype.com/login/skypetoken
Takes an old style skype md5 hash.
- For microsoft accounts: api.skype.com/rps/skypetoken
Takes a ticket token (magic T) for "wl.skype.com"
The only complicated part is getting that token. One way could be to use
oauth with the code that is already implemented, but that's no fun.
Instead, this uses SOAP login (login.live.com/RST.srf) from the MSN era.
A little verbose but very reliable and simpler than scraping HTML.
And it gets decent …
=> Add alternative login methods

skypeweb/purplecompat.h, skypeweb/skypeweb_contacts.c, skypeweb/skypeweb_contacts.h, skypeweb/skypeweb_messages.c
The current implementation completely disregards the "composetime" member of
the received message if its type is RichText/UriObject or
RichText/Media_FlikMsg.
This results in the system messages with links to the images, as well as the
images themselves having the timestamp of the message's reception by the
client instead of the time when the message was actually sent.
=> Use the correct timestamp for image messages

skypeweb/skypeweb_contacts.c
If "greeting" is not available in the invite notification that's received from
the server, use the "message" field from the object found in the "invites"
array.
=> Fix #562 : Invite message not displayed

skypeweb/libskypeweb.c
Remove the empty option which shows up as an unlabeled check box in the account settings tab.
=> Remove the empty option from account settings

skypeweb/libskypeweb.c, skypeweb/libskypeweb.h, skypeweb/skypeweb_connection.c, skypeweb/skypeweb_contacts.c, skypeweb/skypeweb_contacts.h
This PR adds support for the "People you may know" functionality found in the Skype desktop client, available while adding people to a chat.
The desktop client obtains the address and parameters of the "people suggestions" endpoint by making an appropriate call to `b.config.skype.com`, which supplies the address and the parameters which then are passed as `X-RecommenderServiceSettings`. Accessing the config resource also sends back the `ETag` header, which then must be passed into the endpoint as `X-ECS-ETag`. It is also necessary to provide a `X-Skype-Client` header.
However, during my testing, I found out that the server doesn't seem to care about the actual content of `X-ECS-ETag` or `X-Skype-Client` and accepts pretty much anything. Since accessing the config endpoint would be a much …
=> Implement support for contact suggestions

skypeweb/skypeweb_messages.c
Adds the "Users" column to the room list, which displays the current number of users.
=> Display the number of members in chat rooms

skypeweb/skypeweb_contacts.c
See https://github.com/EionRobb/skype4pidgin/issues/590
I got sidetracked from doing the long version but at least this fixes the bug with losing the mood after the info update.
=> skypeweb_got_info(): Do not clear mood if it's null (it's always null via this call)

skypeweb/skypeweb_contacts.c
There is one parentheses more than needed.
=> Fix compilation error

skypeweb/skypeweb_login.c
I wonder if it is a usefull addition for every "Failed getting *" string?
Just let me know!
=> as suggested in #601

skypeweb/skypeweb_contacts.c
As I mentioned in #616, the plugin is crashing when try to send a file. The origin of problem was in error handling code. This PR should fix the error that can not be properly handled by the plugin and does nothing with the error in error handling code itself.
First of all it fixes the `"{\\"message\\":\\"PlatformId needs to be specified\\"}"` server message by [supplying the platform id within the header](https://github.com/EionRobb/skype4pidgin/compare/master...xomachine:master#diff-a0bf7cdc1a25b64b019dba61e1971a58R754).
After fixing this problem I've encountered another one: the server does not react on the file transfer performed by ssl code. So I've just switched to `purple_http_request_set_contents_reader` as it mentioned in TODOs. Now the file transfer works for me.
=> Fix for a file transfer

skypeweb/libskypeweb.c, skypeweb/skypeweb_login.c, skypeweb/skypeweb_login.h
That error is basically a 404 that you get when you set Accept to json
in the api.skype.com server.
The fix is to grab a new rps URL from skypeweb, it lives in the 'rps'
server (edge.skype.com) and has a slightly different path.
This also removes the 'skyper' md5-based login. It's still referenced in
the javascript of skypeweb, but probably unused because the endpoint is
the same we're hitting here and it's dead.
SOAP login still works with no issues, for both skype usernames and
microsoft accounts (it didn't work with skype usernames when i first
wrote this, but i remember at some point later throwing skype usernames
at the SOAP login and having it work)
For #639
=> Fix "No handler found for resource" on alt login

skypeweb/skypeweb_login.c
There is variable typo causing build error.
/home/user/src/skype4pidgin/skypeweb/skypeweb_login.c: In function ‘skypeweb_login_got_t’:
/home/user/src/skype4pidgin/skypeweb/skypeweb_login.c:168:2: error: ‘error_test’ undeclared (first use in this function); did you mean ‘error_text’?
error_test = skypeweb_string_get_chunk(data, len, ",sErrTxt:'", "',Am:'");
^~~~~~~~~~
error_text
/home/user/src/skype4pidgin/skypeweb/skypeweb_login.c:168:2: note: each undeclared identifier is reported only once for each function it appears in
/home/user/src/skype4pidgin/skypeweb/skypeweb_login.c:160:9: warning: unused variable ‘error_text’ [-Wunused-variable]
gchar *error_text;
^~~~~~~~~~
CMakeFiles/skypeweb.dir/build.make:110: recipe for target 'CMakeFiles/skypeweb.dir/skypeweb_login.c.o' failed
make[2]: …
=> Fix build error (variable typo)

skypeweb/libskypeweb.c
When entering a group chat, skypeweb would explicity specify the user role
which could lead to a users role being downgraded from admin to user.
Removes explicit specifying the role so that what ever role we are given
is preserved.
=> Fix loss of admin rights when entering a group

skypeweb/skypeweb_login.c
M$ had enabled and disabled it recently, and who knows how many times they'll do it again. It should better be optional, so the users won't have to install different plugin versions every time.
=> Make the opid stage optional

skypeweb/skypeweb_contacts.c
As far as I could tell from testing and by quick look at code (https://github.com/bitlbee/bitlbee/blob/75222ab2b4542ee8b4726feee0d2c65636e3c7e3/protocols/purple/purple.c#L1182-L1186) BitlBee does not handle PURPLE_MESSAGE_SYSTEM and hence links to images are not visible anywhere. This PR attempts to fix it by posting image URL as normal IM/Chat message. Works for me though admittedly this is my "first time" with libpurple code and might have some issues.
=> Switch BitlBee image message from system to normal IM/Chat

skypeweb/skypeweb_messages.c
It appears that Skype client is very sensitive to type of message that
is being sent. Implicit linkifing through `purple_markup_linkify()` for
some reason adds links with uppercase "<A HREF" which is ignored by
skype client. While Pidgin itself seems to handle it correctly, it is
not the case for all libpurple clients ie BitlBee. Follow other
protocols (ie Jabber) and ensure message is XHTML before sending.
=> Ensure sent message is in XHTML format

skypeweb/skypeweb_contacts.c, skypeweb/skypeweb_contacts.h, skypeweb/skypeweb_messages.c, skypeweb/skypeweb_messages.h
Message looks almost the same as image attachment hence logic is almost
the same. For now Pidgin displays thumbnail + link to full video while
Bitlbee shows link.
=> Preliminary video attachment support

skypeweb/skypeweb_connection.c, skypeweb/skypeweb_login.c, skypeweb/skypeweb_messages.c
It mitigates a common cause of segmentation faults due to a freed
SkypeAccount structure which may contain corrupted data already,
still the sa->pc may be NULL as it is freed right before the whole
structure. It does not guarantee the crash prevention though, and does
not solve the root problem, as these callbacks should be removed and
not invoked if an account is disconnected.
The crash backtraces are collected in #650, most of them happened in
`skypeweb_post_or_get`.
=> sa->pc safety check in request/timeout callbacks
