EionRobb/skype4pidgin

skypeweb/CMakeLists.txt

Fix the liblibskypeweb issue in the cmake configuration file

Fix the liblibskypeweb issue

---

skypeweb/README.md

Added rpmbuild instructions into readme file.

Added rpmbuild instructions

---

skypeweb/CMakeLists.txt

Forgot to copy the icons in the system during the packaging

Package correctly the library with the icons

---

skypeweb/libskypeweb.c

connect/disconnect conversation-updated signal

---

skypeweb/skypeweb_login.c

Skypeweb: Fix microsoft account login (post.srf needed MBI_SSL policy)

---

skypeweb/skypeweb_connection.c
skypeweb/skypeweb_contacts.c
skypeweb/skypeweb_login.c
skypeweb/skypeweb_messages.c

This fixes a few compiler warnings I get on Ubuntu 14.04 with CC 4.8.4.

Fix compiler warnings

---

skypeweb/README.md
skypeweb/purple-skypeweb.spec

Updated SPEC to version 1.0

---

skypeweb/README.md
skypeweb/purple-skypeweb.spec

Fixed SPEC file

---

skypeweb/README.md

As it happens, I kind of did this last night, just wasn't sure it was worth making a github repo for or sending patch, etc etc.

Add instructions for building and installing on Debian/Ubuntu/Mint.

---

skypeweb/README.md

sorry for the delay; this should resolve #369

skypeweb archlinux install instructions

---

skypeweb/README.md

Added COPR repository into Readme.

Added COPR repository into Readme

---

skypeweb/README.md

Followup of https://github.com/EionRobb/skype4pidgin/pull/464.

Fixed the openSUSE package link.

---

skypeweb/Makefile

Added LDFLAGS support.

---

skypeweb/README.md

Just updated the Ubuntu version deb creation instructions.  Everything else seems to work nicely.

update install instructions for latest version.

---

skypeweb/skypeweb_contacts.c
skypeweb/skypeweb_login.c
skypeweb/skypeweb_messages.c

This is a rewritten version from the former and now abolished pull request #503, which see for code review discussions. Thanks for the review.
Note that I have force updated my branch.

[v2] pull request to fix %.*s types and drop unused variables/assignments.

---

libskype.c

libskype: Don't use freed memory.  Don't expect the passed-in call number string to stay around, so duplicate it if needed.
Also fix a memory leak when media creation failed in `skype_media_initiate()`.

Fix answering calls (with pidgin-skype)

---

skypeweb/skypeweb_contacts.c
skypeweb/skypeweb_contacts.h
skypeweb/skypeweb_messages.c

add RichText/Contacts event handler

add receive contacts (RichText/Contacts) function

---

skypeweb/libskypeweb.c
skypeweb/libskypeweb.h
skypeweb/skypeweb_contacts.c
skypeweb/skypeweb_contacts.h
skypeweb/skypeweb_messages.c
skypeweb/skypeweb_messages.h

RichText/Media_FlikMsg event handler.
RichText/Contacts event handler small fix.

add receive Moji (RichText/Media_FlikMsg) function

---

skypeweb/Makefile

Fixed incorrect chmod on installed by makefile files.

Fixed incorrect chmod on installed by makefile files

---

skypeweb/skypeweb_messages.c

When re-joining a previously joined chat, skypeweb requests the full message
history from the Skype server. This leads to re-displaying messages that are
already present in the conversation logs stored on the disk, if logging is
enabled.
This commit stores the last message timestamp of all group chats for which a
message has been received. Using the "global" last message timestamp is not
possible, since messages in a given group chat might have appeared between
leaving and re-joining.

Store the last message timestamp of group chats

---

skypeweb/CMakeLists.txt

See https://github.com/EionRobb/skype4pidgin/pull/567#issuecomment-327419161

Avoid CXX checks

---

skypeweb/skypeweb_login.c

please try logging in via browser first

---

skypeweb/skypeweb_login.c

This small change will give you a message and error code back from Skype when the login fails. For example, it will tell you that your account is blocked, or that you are required to enter a 2FA value.

Give a detailed login failure message

---

skypeweb/purple-skypeweb.spec

This updates the `purple-skypeweb.spec` file to the latest version.
Please, consider updating the rpm spec when doing a version bump.
Thanks,
Val.

Update purple-skypeweb.spec to v1.7

---

skypeweb/skypeweb_login.c

Inspired by https://github.com/EionRobb/purple-googlechat/commit/a68a48600baceb55ad608d9603e85d43d0edf566

Fix account disabling on a connection failure on PPFT stage
